# Generated by Django 5.0 on 2023-12-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
