# Generated by Django 5.0 on 2023-12-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_note_last_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='last_modified_at',
        ),
        migrations.AddField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
